name: Kwiki-PrinterFriendly
version: 0.13
abstract: Kwiki Printer Friendly Plugin
author: Henry Laxen <nadine.and.henry@pobox.com
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
